### ISSUE TITLE
Outdated react-router-dom

### ISSUE THREAD

**Issue by renaauerbach** [Tammibriggs/Firebase_user_auth#1]
Your app seems to be dependent on an outdated version of `react-router-dom`. `Redirect` and `Switch` are both deprecated. Can you update? You're app has been very helpful to me otherwise.

**Comment by Tammibriggs** [comment]
Thanks for pointing that out. I will update the **main** branch right now, but updating the **starter**  branch is not an option for now because I used it to write an article. I will need to send a request to update the article before updating the **starter** branch.

**Comment by Tammibriggs** [comment]
Done
